version: '3.8'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_ssh
    volumes:
      - .:/app
    ports:
      - "2222:22"  # SSH port forwarding
    command: /usr/sbin/sshd -D  # Run SSH daemon
    environment:
      - AUTHORIZED_KEYS=minsu201  # Set your SSH public key for authentication
    networks:
      - app-network

networks:
  app-network:
    driver: bridge